### PR TITLE
[BCCAFUS-2] Develop a Product Page using HTML

### PR DESCRIPTION
**Pull request by elijahcod3s**
My product page Assignment
Webpage
Webpage2

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done, @elijahcod3s! I observed that the log files are not present in your PR, irrespective of the fact that you ran the test. Kindly ensure when adding the files that you add the files one after the other by running "git add < filename>" instead of adding all the files at once by running "git add  . " . You'll be able to see the log files in your PR this way.

For further clarification, please do not hesitate to reach out to me at @Bukky on Slack.

**Comment by Mayowa2020** [comment]
Hello @elijahcod3s For each task, please ensure you add the screenshots of your webpage and not the screenshot of the git bash.

**Comment by elijahcod3s** [comment]
Hi Bokola,

How do I resolve this issue?

Elijah

**Comment by elijahcod3s** [comment]
> Well done, @elijahcod3s! I observed that the log files are not present in your PR, irrespective of the fact that you ran the test. Kindly ensure when adding the files that you add the files one after the other by running "git add < filename>" instead of adding all the files at once by running "git add  . " . You'll be able to see the log files in your PR this way.
> 
> For further clarification, please do not hesitate to reach out to me at @bukky on Slack.

**Pull request closed without merging**
