### PR TITLE
[DGPFUS-162] Create & Style the Landing Page for a Food Orderin

### PR DESCRIPTION
**Pull request by Maurice-Jah**
- I created the landing page
Screenshot (725)
Screenshot (726)

### CODE REVIEW

**Review by Maurice-Jah — COMMENTED** [review]
I dont know what else to do

**Comment by Maurice-Jah** [comment]
I want a fresh one

**Comment by ToluEnny24** [comment]
@Maurice-Jah welldone, i noticed you had so many issues running your tests and adding the logfile,

**Review by ToluEnny24 — APPROVED** [review]
Reviewed manually...

**Pull request merged**
