### PR TITLE
[DGPFUS-112] Develop a List View for Customer Orders

### PR DESCRIPTION
**Pull request by chivicoko**
- added index1.php file as the order details view
Screenshot (225)

### CODE REVIEW

**Comment by chivicoko** [comment]
Screenshot (224)

- This is the screenshot of the recent webpage

**Comment by chivicoko** [comment]
Screenshot (222)

- This is one is the screenshot of the order details webpage

**Comment by chivicoko** [comment]
Screenshot (225)

- this is the current Order details webpage

**Comment by chivicoko** [comment]
Screenshot (225)

- this is the current Order details webpage

**Review by Mayowa2020 — APPROVED** [review]
Well done @chivicoko! **Approved.**

**Pull request merged**
