### PR TITLE
[HIRFUS-163] Create & Style the Vendors Page for a Food Orderin

### PR DESCRIPTION
**Pull request by Kutembachinambu**
image

image

image

image

### CODE REVIEW

**Comment by ToluEnny24** [comment]
Well done @Kutembachinambu have you added the omits and should I go ahead to merge this?

**Comment by Kutembachinambu** [comment]
Hey, I have added.  Is it possible to add different screenshot?

Sent from Yahoo Mail on Android 
 
  On Sat, 26 Feb 2022 at 23:39, ***@***.***> wrote:   


Well done @Kutembachinambu have you added the omits and should I go ahead to merge this?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kutembachinambu** [comment]
Kindly go ahead and merge.

Sent from Yahoo Mail on Android 
 
  On Sat, 26 Feb 2022 at 23:39, ***@***.***> wrote:   


Well done @Kutembachinambu have you added the omits and should I go ahead to merge this?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by ToluEnny24 — APPROVED** [review]
Manually reviewed...

**Pull request merged**
