### PR TITLE
[DGPFUS-2] Develop a Product Page using HTML

### PR DESCRIPTION
**Pull request by Raphylee**
This is my Ecommerce Website built only using HTML

### CODE REVIEW

**Review by ToluEnny24 — CHANGES_REQUESTED** [review]
Manually reviewed, however i have the following, feedbacks, your e commerce page didnt meet all  the success criteria.You should have description, price of the product, please make the required changes to your files

**Comment by ToluEnny24** [comment]
@Raphylee whats happening? Do you need help?

**Comment by Raphylee** [comment]
Dear Tolu,

Thanks for checking.

I have been given a review requiring me to do a modification to my work.

So it's pending on me.
I will work on this, power has just been a bottleneck lately but I'm
working around it.

I believe one I can provide the expected modifications and do the PR all
will be well.

Warm regards,
Raphael

**Review by ToluEnny24 — APPROVED** [review]
Manually reviewed and changes fixed...

**Pull request merged**
