### PR TITLE
[DGPFUS-168] Create the Cart Page with REACT

### PR DESCRIPTION
**Pull request by Timilehin08**
cartdesktop
cartmobile

### CODE REVIEW

**Comment by Timilehin08** [comment]
@ToluEnny24 @Mayowa2020  when i try to run tests, it says no such file or directory, hence why no logfile is present

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Hello @Timilehin08, I am unable to view your code in the react-app folder. Kindly make the required changes and revert when done

**Comment by Timilehin08** [comment]
@Mayowa2020 I don't know what's wrong and why it isn't showing. It's under the reactapp in the folder, so i don't know what changes I'm to make. I've pushed it again

**Comment by Timilehin08** [comment]
Okay the files changed are showing now @Mayowa2020

**Comment by Mayowa2020** [comment]
Well done @Timilehin08, in your CSS file, kindly indicate the media query for the mobile screen/view/port.

**Comment by Timilehin08** [comment]
Done @Mayowa2020

**Review by Mayowa2020 — APPROVED** [review]
Well done @Timilehin08! **Approved**

**Pull request merged**
