### PR TITLE
[NDFFET-166] Landing Page Validation

### PR DESCRIPTION
**Pull request by Hossanna**
Screenshot (89)

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Hello @Hossanna, It's been a while, since you worked on your code.

**Comment by Hossanna** [comment]
Screenshot (82)

**Comment by Hossanna** [comment]
Screenshot (83)

Screenshot (82)

**Comment by Mayowa2020** [comment]
Well done @Hossanna! Please ensure you run the test on your code. Thanks!

**Comment by Hossanna** [comment]
Screenshot (89)

**Review by Mayowa2020 — APPROVED** [review]
Well done @Hossanna! **Approved.**

**Pull request merged**
