### PR TITLE
[DGPFET-164] Responsive E-commerce Landing Page

### PR DESCRIPTION
**Pull request by UshieChris**
Screenshot (1)
Screenshot (2)

### CODE REVIEW

**Comment by ToluEnny24** [comment]
@UshieChris click on the third cross, you have codefactor error to fix

**Comment by ToluEnny24** [comment]
@UshieChris It is been a while, are you fine?

**Comment by UshieChris** [comment]
I don't know how to resolve that error, I was seeing that my code and
someone else conflict, I don't know how that should stop my code from being
merge, so I don't know what to do

**Comment by UshieChris** [comment]
I don't know how to resolve that error, it's showing me down and frustrating me in a way since I have no idea of how my code conflict with someone else

**Comment by ToluEnny24** [comment]
You do not know how to resolve it and you could not reach out for help or
support for the last 6 days...

When you are ready then.

**Comment by ToluEnny24** [comment]
@UshieChris The conflicts you have are from errors you made on your own file. You have duplicate properties in the same selector block, you have 0px instead of 0 and yet you claim you dont know how to go about it. I will close this Pull Request when you are ready you push and correct your errors.

**Comment by UshieChris** [comment]
Okay, I will go through it again today

**Comment by UshieChris** [comment]
You seem very angry with me.
I'm sorry, if I hurt you!

**Comment by ToluEnny24** [comment]
Hi Chris, I got angry because you didn't reach out about the issues you
had... In Dufuna we have a support system made available for you, I was
wondering what was wrong with you only to find out you were okay but just
assumed and didn't reach out.....

Another statement you made was "how that would make your task not to be
merged". The Repo is quite important to us and should not be tampered with.
It must have been because I fixed the codefactor error for you in previous
tasks.

I realized fixing without having the scholar fix was spoon-feeding and not
good for training up or the learning process.
If you have issues send a DM to me on Slack. I am @Tolulope

Take care..

**Pull request merged**
