### PR TITLE
[DGPFUS-164] Responsive E-commerce Landing Page

### PR DESCRIPTION
**Pull request by Don2kay**
Landing page media query added

### CODE REVIEW

**Review by Mayowa2020 — COMMENTED** [review]
Well done @Don2kay   Please send in the screenshots of these pages. Thank you!

**Comment by Mayowa2020** [comment]
Hello @Don2kay, hope you doing great. Reaching out to you, to confirm if you're experienecing any blockers. Kindly effect the requested changes and tag me @Mayowa2020 and @Bukky on Slack, once you're done effecting the changes.

**Comment by Don2kay** [comment]
Screenshot 2022-08-05 122712
Screenshot 2022-08-05 122446
Screenshot 2022-08-05 122621

**Review by Mayowa2020 — APPROVED** [review]
Well done @Don2kay! Approved...

**Pull request merged**
