### PR TITLE
[DGPFUS-3] Develop a Contact Form Page using HTML

### PR DESCRIPTION
**Pull request by rid14real**
I built an HTML form for my contact page.

contact form

### CODE REVIEW

**Review by Mayowa2020 — DISMISSED** [review]
Well done, @rid14real. Please try running the test to check your code.

**Comment by rid14real** [comment]
Thank you very much @Mayowa2020. I have tried many times but it is not working as expected. Please, see the response I keep getting below.

 
test error

**Comment by Mayowa2020** [comment]
Well done @rid14real. Kindly reach out to me on Slack @Bukky so I can walk you through the test process.

**Comment by rid14real** [comment]
Thank you very much @Mayowa2020. I will do that now.

**Comment by rid14real** [comment]
@Mayowa2020, please, I don't know what's wrong. I have ensured all the tests passed locally. However, it's not merging here. I appreciate your help.

**Pull request merged**
