### PR TITLE
[DCSFUS-168] CREATE THE CART PAGE WITH REACT

### PR DESCRIPTION
**Pull request by bayooba**
This is my submission for the first task in the React module. Glad that I can finally make this PR after a long time. Attached is the screenshot of the page. Thank you.

cart
cart_android

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @bayooba! Could you correct the CodeFactor errors in your code? I also noticed that you have someone else's code in your PR.

Please make the required changes and revert when done.

**Comment by Mayowa2020** [comment]
Hello @bayooba, Why am I seeing codes for pages that are yet to be merged? Kindly remove all the commented codes and codes relating to those tasks that are yet to be merged. Thanks!

**Comment by bayooba** [comment]
> Hello @bayooba, Why am I seeing codes for pages that are yet to be merged? Kindly remove all the commented codes and codes relating to those tasks that are yet to be merged. Thanks!

**Comment by bayooba** [comment]
Closing the PR earlier was a mistake.

**Comment by bayooba** [comment]
Hello, please kindly review the PR.

**Review by Mayowa2020 — APPROVED** [review]
Well done @bayooba! **Approved**

**Pull request merged**
