### PR TITLE
[DGPFUS-160] My First Pull Request

### PR DESCRIPTION
**Pull request by Calenn1**
- This is my first pull request.
- In this PR, I have added some details about myself ,and challenges I have faced.

### CODE REVIEW

**Comment by ToluEnny24** [comment]
@Calenn1 What exactly are you trying to do please?

**Comment by ToluEnny24** [comment]
The instruction was make slight changes, I did not ask you to delete the file

**Comment by Calenn1** [comment]
I was trying to delete it so I can start all over again.

**Comment by Calenn1** [comment]
When I made the changes and tested it(as required), it refused to commit.

**Review by ToluEnny24 — APPROVED** [review]
I really hope you do not end up having conflicting files.... However @Calenn1 well done. So another way to start again is deleting the entire dufuna folder that you have on your local machine and re cloning the remote repo, this way you are starting on a clean slate with files in the master branch.

**Comment by Calenn1** [comment]
> I really hope you do not end up having conflicting files.... However @Calenn1 well done. So another way to start again is deleting the entire dufuna folder that you have on your local machine and re cloning the remote repo, this way you are starting on a clean slate with files in the master branch.

Thank you so much. I'll do just that.

**Pull request merged**
