### PR TITLE
[DGPFUS-167] Vendors Page Validation 

### PR DESCRIPTION
**Pull request by Daslaw**
Screenshot 2022-08-15 at 18-42-49 FoodBag-Vendors Page

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Daslaw! Please, attach also the Screenshot of the webpage when there are no items in the cart.

**Comment by Daslaw** [comment]
Screenshot 2022-08-16 at 10-08-30 FoodBag-Vendors Page

**Review by Mayowa2020 — APPROVED** [review]
Well done @Daslaw! Approved..

**Comment by Daslaw** [comment]
Application is not updated, I will re-pull the task.

**Pull request merged**
