### PR TITLE
[DGPFUS-10] THE SOFTWARE DEVELOPER CONDITIONALS

### PR DESCRIPTION
**Pull request by Victorious-Toluwalope**

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Victorious-Toluwalope!  Your solution appears to be muddled. Try adding line breaks to make it look more professional. As soon as you're finished, be sure to attach the screenshot of the website.

**Comment by Victorious-Toluwalope** [comment]
snip1
snip2
snip3
snip4


Changes made

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Hello @Victorious-Toluwalope, why do you have two tasks in this PR? These tasks have different titles, hence the need to separate them. If not, you will have issues moving on to the next module.

Kindly do the needful and revert when done.

**Comment by Victorious-Toluwalope** [comment]
Hello @Mayowa2020, thank you for pointing out my error.
I have done the needful.

**Review by Mayowa2020 — APPROVED** [review]
Well done @Victorious-Toluwalope! **Approved**

**Pull request merged**
