### PR TITLE
[DCSFUS-166] Landing Page Validation

### PR DESCRIPTION
**Pull request by Preshy27**
DOM-1
DOM-2
DOM-3

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Preshy27! You are yet to complete this task:
Ensure that when a customer selects an interest, the customer should be redirected to the Vendor page.

Please make update your task and revert when done.

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Preshy27! I have tried running your code, but it's not running at its should. For example when I click on the mages, it takes me no where as opposed to taking me to the vendor's page. 
For further clarification, please go through this DOM Tutorial by clicking on this link below 👇  https://www.youtube.com/watch?v=FIORjGvT0kk&list=PL4cUxeGkcC9gfoKa5la9dsdCNpuey2s-V

**Comment by Preshy27** [comment]
> Well done @Preshy27! I have tried running your code, but it's not running at its should. For example when I click on the mages, it takes me no where as opposed to taking me to the vendor's page. For further clarification, please go through this DOM Tutorial by clicking on this link below 👇 https://www.youtube.com/watch?v=FIORjGvT0kk&list=PL4cUxeGkcC9gfoKa5la9dsdCNpuey2s-V

Good morning @Mayowa2020 I've resolved the issue now. Some of my files got deleted somehow so the vendor page couldn't display

**Review by Mayowa2020 — APPROVED** [review]
Well done @Preshy27! Approved.

**Pull request merged**
