### PR TITLE
[BCCAFUS-40] Querying the Transportation Database

### PR DESCRIPTION
**Pull request by elijahcod3s**
This PR contains the queries and their results from the transport company database.

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done, @elijahcod3s! Kindly ensure you run the test. Make sure your queries are correct so as to be able to obtain the right answers to the given questions.

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @elijahcod3s! Please state the number of passengers involved in question 4.

**Comment by elijahcod3s** [comment]
I stated in the comment below the sql command. I will edit to be more clear

Elijah

**Comment by Mayowa2020** [comment]
Hello @elijahcod3s, so sorry I meant to write question 5.

**Comment by elijahcod3s** [comment]
Ok. Doing so now. The assignment guidelines only request comments
for queries 1, 2, and 4.

**Review by Mayowa2020 — APPROVED** [review]
Well done @elijahcod3s! **Approved**

**Comment by elijahcod3s** [comment]
Thank you.

**Pull request merged**
