### PR TITLE
[DGPFET-9] Printing Product Price with JavaScript

### PR DESCRIPTION
**Pull request by blessingOluwapelumi**

### CODE REVIEW

**Review by Mayowa2020 — APPROVED** [review]
Well done @blessingOluwapelumi, please attach the screenshots of your result for proper review.

**Comment by blessingOluwapelumi** [comment]
image

**Comment by blessingOluwapelumi** [comment]
> Well done @blessingOluwapelumi, please attach the screenshots of your result for proper review.

I have added the screenshot as requested.
also, i realized it mistakenly linked a wrong JS file which i have now corrected and updated my PR.

Thanks.

**Review by Mayowa2020 — APPROVED** [review]
Well done @blessingOluwapelumi , I have had to make the required changes to the final output of comply witn the task given. I removed the img tag, and replaced it with  just the imageURL.

**Comment by blessingOluwapelumi** [comment]
Okay,
Thanks for the correction,
I will not add that next time.

**Pull request merged**
