### PR TITLE
[DGPFUS-170] Create the Success page using REACT

### PR DESCRIPTION
**Pull request by Adezayn**
Screenshot 2022-10-19 at 21 49 17
Screenshot 2022-10-19 at 21 50 02

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Hello @Adezayn, I noticed you have some unused codes in your task that you commented out.  I actually forgot to mention this in your previous task; please remove them. This helps to make your code neat and more readable.

**Comment by Mayowa2020** [comment]
**Kindly make the requested changes and revert when done.**

**Comment by Adezayn** [comment]
Alright, thank you.

**Review by Mayowa2020 — APPROVED** [review]
Well done @Adezayn! **Approved.**

**Pull request merged**
