### PR TITLE
[DCSFUS-4] Add Page Navigation

### PR DESCRIPTION
**Pull request by Preshy27**
Page Navigation

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Preshy27 ! Please run the test on your code.

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
For easy identication, please different your index.html files, by naming one product.html and the other contact.html.

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
KIndly effect the changes and revert when done.

**Comment by ToluEnny24** [comment]
Hi @Preshy27 Your PR title is wrong so I will be closing this PR

**Pull request closed without merging**
