### PR TITLE
[DCSFUS-93] HOW'S THE WEATHER?

### PR DESCRIPTION
**Pull request by bayooba**
My submission for the third task in the php module. Attached is the screenshot. Thank you.

weather_task

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Well done @bayooba! Please run the test on your code.

**Comment by Mayowa2020** [comment]
Well done, @bayooba. I am unable to resolve the conflict issues as stated above from my end. Please follow the instructions above to be able to resolve this on your end.

**Comment by bayooba** [comment]
@Mayowa2020 I have resolved the merge conflict.

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done, @bayooba  for the progress so far, but I can detect a slight error in your code. 

Please go through the documentation in this link to detect your error: https://www.javatpoint.com/php-if-else#if-else-if .

**Pull request merged**
