### PR TITLE
[NDFFET-10] The Software Developer Conditionals

### PR DESCRIPTION
**Pull request by Hossanna**

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Hossanna, Please remove any unused code that does belong to this task.

**Comment by Hossanna** [comment]
Thank you ma'am @Mayowa2020. Removed.

**Comment by Mayowa2020** [comment]
Well done, @Hossanna! Please attach the screenshot of your webpage.

**Comment by Hossanna** [comment]
Screenshot (28)

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done, @Hossanna. Your webpage looks muddled up. Why don't you allow each expression to fall on a new line?

**Comment by Hossanna** [comment]
Screenshot (30)

**Review by Mayowa2020 — APPROVED** [review]
Well done, @Hossanna. **Approved**

**Pull request merged**
