### PR TITLE
[DCSFUS-2] Develop a Product Page Using HTML

### PR DESCRIPTION
**Pull request by divinej**
- In this PR I created a product page Using HTML only

### CODE REVIEW

**Review by divinej — COMMENTED** [review]
Change

**Review by Mayowa2020 — APPROVED** [review]
Well done @divinej !  You are expected give two product names with their images and descriptions: one each for each product. Please ensure you attach the Screenshots of your webpages to your PR when done. Kindly effect changes and revert. Thank you

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
@divinej, Please your PR is yet to be approved. Kindly effect the requested changes, thank you,

**Review by Mayowa2020 — APPROVED** [review]
Well done @divinej ! Approved...

**Pull request merged**
