### PR TITLE
[DGPFET-170] Create the Success page using REACT

### PR DESCRIPTION
**Pull request by UshieChris**

### CODE REVIEW

**Comment by Mayowa2020** [comment]
@UshieChris, hope you doing great. Reaching out to you, to confirm if you're experiencing any blockers. Kindly effect the requested changes and tag me @Mayowa2020 and @Bukky on Slack, once you're done effecting the changes.

**Comment by ToluEnny24** [comment]
@UshieChris you need to attach the screenshot of the page you created.

**Review by Mayowa2020 — APPROVED** [review]
Well done @UshieChris ! Approved...

**Comment by UshieChris** [comment]
Good evening ma, I still have one pending

**Pull request merged**
