### PR TITLE
[DGPFET-8] Research Programming Languages

### PR DESCRIPTION
**Pull request by Usmaniyya**
Check my PR

### CODE REVIEW

**Comment by Usmaniyya** [comment]
You have access to it.

**Comment by Usmaniyya** [comment]
Screenshot from 2022-07-04 13-04-04

**Comment by ToluEnny24** [comment]
Hi @Usmaniyya I still do not have access to what you have done. Inside the dialog box of the general share option is where you have restricted. Click on the dropdown and allow anybody with the link to view.

**Comment by Usmaniyya** [comment]
Check now

**Review by ToluEnny24 — APPROVED** [review]
Well done on your research @Usmaniyya

**Pull request merged**
