### PR TITLE
[DCSFUS-170] CREATE THE SUCCESS PAGE USING REACT

### PR DESCRIPTION
**Pull request by bayooba**
This is my submission for the final task in the REACT module.
The screenshots are attached. Thank you.

order_success
ordersuccess_android

### CODE REVIEW

**Comment by bayooba** [comment]
@Mayowa2020 the pull request behaved as it did the last time when I pushed for the verification page task. 
My observation for this behaviour is this: files that were not changed at the time of this PR were not staged for pushing to remote repo because they had been merged and therefore no changes were tracked compared to what exists in the remote repo. The files exist in the "../submissions/adebayoObafemi/REACT/react-app" folder but were not staged because there were no changes made to the other files.

So I had to do some edits to these files so as to be able to add all the files for this final task i n this PR.

Should it turn out that this current submission will generate conflict with my previous work, kindly notify me and I'll make necessary correction. I look forward to your review and your observation about my opinion mentioned above. 
Thank you, always.

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @bayooba! Please be mindful, though, that lines 69 to 90 of your PR still include unused codes.
Kindly make the required changes.

**Comment by bayooba** [comment]
Thank you very much @Mayowa2020. It was an oversight. I have made the changes. Once again, thank you, always.

**Review by Mayowa2020 — APPROVED** [review]
Well done @bayooba! **Approved**

**Pull request merged**
