### PR TITLE
[DGPFUS-8] Research Programming Languages

### PR DESCRIPTION
**Pull request by Bunmi194**

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
@Bunmi194 Well done! Please for this task, change your sharing option from restricted to anyone with this link can view.

**Comment by Bunmi194** [comment]
@Mayowa2020 Thanks! I just did that

**Review by Mayowa2020 — APPROVED** [review]
Well done @Bunmi194 Check out the updates I made on the C++ and Scalar Languages.

**Review by Mayowa2020 — APPROVED** [review]
Well done @Bunmi194 ! Check out updates  made to the C++ and Scala programming languages.

**Review by Mayowa2020 — DISMISSED** [review]
Well done @Bunmi194 Approved! Check the updates made to the C++ and Scala Programming Languages

**Review by Mayowa2020 — APPROVED** [review]
Well done @Bunmi194

**Review by Mayowa2020 — DISMISSED** [review]
Well done @Bunmi194 !

**Review by Mayowa2020 — APPROVED** [review]
Well done @Bunmi194! Approved..

**Pull request merged**
