### PR TITLE
[DGPFUS-2] Develop a Product Page using HTML

### PR DESCRIPTION
**Pull request by chivicoko**
- I added an index.html file with an Ecommerce home page

### CODE REVIEW

**Review by ToluEnny24 — CHANGES_REQUESTED** [review]
The success criteria for this task is using only two images and also attaching a screenshot of the output when viewed on your browser. @chivicoko Well done on this task. However I want you to do the following, 
1) Remove the excess images
2) Attach a screenshot
3) Test your work locally and attach the logfiles.

**Comment by chivicoko** [comment]
- @ToluEnny24 I noticed there is no test file for my html module in my test folder. What do I do?
- How do I now attach a screenshot of the page here? And I just want to be if I took the correct screenshot; I attached it below.
Screenshot (116)
Screenshot (118)

- I have removed the extra 2 images in my html file.

**Comment by chivicoko** [comment]
@ToluEnny24 , From what I just found, I think the two images I just added now in my initial comment should be able to satisfy the need.
How to do local test of the task is what I am not certain about. Please help me out.

**Comment by ToluEnny24** [comment]
Hi hi Victor @chivicoko, the two images you used are sufficient, and the screenshot you attached is the correct one.

However concerning the test folder you are looking for, I will ask that you fix a meeting with Bukky on slack so she shows you your way around the test, while at that I will manually review this PR so you can have a beautiful and smooth journey henceforth.

**Review by ToluEnny24 — APPROVED** [review]

**Pull request merged**
