### PR TITLE
[DCSFUS-3] [DCSFUS-4] My Third Pull Request

### PR DESCRIPTION
**Pull request by Saypauloh**
This is my third pull request.
In this PR, I added page navigation to my pages. I also developed a contact form using HTML.
product page implementation
contact form implementation

.

### CODE REVIEW

**Comment by Ireti203** [comment]
Your PR title is wrong @Saypauloh

**Comment by Ireti203** [comment]
You should use the exact title on the task. And not edit

**Comment by Saypauloh** [comment]
How?
"everything is up to date" is what I got when I tried pushing again

**Comment by Saypauloh** [comment]
I can't push twice. The two tasks in this topic  are interwoven. That was
why I put the two task codes in the pr

**Comment by Saypauloh** [comment]
Change effected

**Pull request closed without merging**
