### PR TITLE
[DCSFUS-8] RESEARCH PROGRAMMING LANGUAGES

### PR DESCRIPTION
**Pull request by OlamyDev**
Programming Language 1 Task

### CODE REVIEW

**Review by chinemeze847 — APPROVED** [review]
well done @OlamyDev! Approved

**Comment by Mayowa2020** [comment]
Hello @OlamyDev, please find attached for your information. You have duplicate copies of the task in your submissions folder.
Screenshot (92)

Kindly remove one, thank you.

**Comment by Mayowa2020** [comment]
Well done @OlamyDev! Please try running the test again, to see if your PR can be automatically merged.

**Review by Mayowa2020 — APPROVED** [review]
Well done @OlamyDev! **Approved.**

**Pull request merged**
