### PR TITLE
[NDFFUS-2] Develop a Product Page using HTML

### PR DESCRIPTION
**Pull request by Loveth15**
This is my product Page.
In this PR, I have made a product page with HTML

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Well done @Loveth15 ! There is no log file present in this pull request. Please ensure that you run the tests locally. Peradventure you run into issues whilst trying to run your test, please do not hesitate to reach out to me @Bukky on Slack.  Thank you!

**Review by Mayowa2020 — COMMENTED** [review]
Hello @Loveth15, Please reach out to me **@Bukky on Slack or @Mayowa2020 on GitHub**. Better still what's your username on Slack, so I can tag you?

**Comment by Mayowa2020** [comment]
Hi @Loveth15, I have tried checking you on Slack with the username you gave above, but the username is not being recognised. Kindly reach out to me instead @Bukky on Slack. Will be expecting you. Cheers!

**Comment by Mayowa2020** [comment]
Hi @Loveth15, instead of creating another PR, please work with this one. All you need to do here is to make the requested changes, then add, commit and push. Do not create another PR

**Comment by Loveth15** [comment]
Hello Bukky,

Currently, if I run the "Git branch -a" command to view my repositories, I
get my repos and other remote repos. What do I do at this point?

**Comment by Loveth15** [comment]
[image: C__WINDOWS_system32_cmd.exe 2022-09-18 14.26.48.png]
Hello @Bukky,

I trust you are well.
I apologize for not getting this, I am still trying to know my way around.
The different repos issue has been cleared, now I still cannot push due to
an error. I will send the image with this mail.

**Comment by VivianEke** [comment]
Screenshot (14)
Screenshot (15)

**Comment by Loveth15** [comment]
Hello @Bukky,

I do not know what to do anymore. The test would not run. I can not push to
the Dufuna repo. I can not proceed to the next step and I can not seem to
find you on Slack. Please help me, I don't know what to do anymore.

**Pull request closed without merging**
