### PR TITLE
[DCSFUS-167] VENDORS PAGE VALIDATION

### PR DESCRIPTION
**Pull request by bayooba**
This is my submission for the second task of DOM Manipulation Module.
I have attached a screenshot too.

DOM_VENDOR_VALIDATION

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Hello @bayooba,  U should have left your HTML and CSS files inside the CSS folder when you created the previous tasks. All that should be in your DOM folder should just be your JS files.

In the process of moving HTML and css files to the DOM folder,  you forgot to change the path to the images too

Where ever you decide to place your HTML and CSS files, ensure the path to the images is correct.

**Comment by bayooba** [comment]
Hello @Mayowa2020, thank you very much for the observation. I have corrected the path to the images and I will take note of that mistake subsequently. Your correction of the mistake has given me a better perspective on how to handle tasks attached to the modules, particularly where you stated that only JS files were expected in the DOM folder.

**Comment by Mayowa2020** [comment]
Well done @bayooba, Please correct the CodeFactor error in your code.

**Comment by bayooba** [comment]
Hello @Mayowa2020, I have resolved the CodeFactor error in my code. Thank you very much for your efforts. Grateful.

**Comment by Mayowa2020** [comment]
Hello @bayooba, I have requested a few more changes.  Please check your slack for updates.

**Pull request closed without merging**
