### PR TITLE
[NDFFET-2] Product Page Using HTML

### PR DESCRIPTION
**Pull request by VivianEke**
Screenshot (1)

### CODE REVIEW

**Comment by VivianEke** [comment]
please I keep seeing this whenever I run the test

**Comment by VivianEke** [comment]
can you please show me where I'm getting wrong

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Hi @VivianEke, in this PR you are expected to display 2 units of product names with their respective images, description, and prices. Please treat as requested and run the test in your code when done. Also, attach the screenshots of your web pages.  If you experience any challenges, kindly reach out to me on Slack @Bukky.

**Comment by VivianEke** [comment]
please I keep seeing error "Seleniun Webdriver not found" each time I run
the test. that's product_page_using html.

**Comment by VivianEke** [comment]
how do I add the log file in my pull request
I've been stuck here for some time now.

**Comment by VivianEke** [comment]
Screenshot (14)
Screenshot (15)

**Comment by Mayowa2020** [comment]
Hello @VivianEke, Your PR is long overdue for approval. Are you really on Slack? I have tried searching for you but to no avail. Somehow, we have to meet, probably on google meet, so I could explain to you the things you have not rightly done in your PR. 
Once again, please reach out to me on Slack @Bukky. Cheers!

**Comment by VivianEke** [comment]
please I'm on slack with this email ***@***.***" I've
been searching for @bukky but haven't found it on slack. if only I knew
your email, it would have been easier.

**Comment by VivianEke** [comment]
please i really need your email so I reach you on slack. mine is
***@***.***
https://join.slack.com/t/vivianeke/shared_invite/zt-1f6o1olpv-4b3IagMufx_M8RD7HZJnHg

**Review by ToluEnny24 — APPROVED** [review]
Manually approved so you can move on  @VivianEke you could reach out to Tolulope on slack for the selenium webdriver error.

**Pull request merged**
