### PR TITLE
[DGPFUS-93] How's the weather?

### PR DESCRIPTION
**Pull request by Maurice-Jah**
- I added weather.php file which contains solution to the php weather task

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Maurice-Jah! Why don't you make the input much more dynamic than it is presently? Different values can be entered at the front end by making it more dynamic.

**Comment by Maurice-Jah** [comment]
> Well done @Maurice-Jah! Why don't you make the input much more dynamic than it is presently? Different values can be entered at the front end by making it more dynamic.

**Comment by Maurice-Jah** [comment]
> Well done @Maurice-Jah! Why don't you make the input much more dynamic than it is presently? Different values can be entered at the front end by making it more dynamic.

If I get correctly, you want me to allow users to input the temperature rather than making it static?

**Comment by Mayowa2020** [comment]
Hello @Maurice-Jah, Yes I wanted you to enable users to be able to input the temperature rather than making it static. But since the git bot has already approved your PR, I will just go ahead and do the same.

**Review by Mayowa2020 — APPROVED** [review]
Well done @Maurice-Jah! **Approved**

**Pull request merged**
