### PR TITLE
[DCSFUS-166] Landing Page Validation

### PR DESCRIPTION
**Pull request by fchinyanta**
--My update 
image

### CODE REVIEW

**Review by ToluEnny24 — CHANGES_REQUESTED** [review]
homeR.html, signProducts.html are not necessary. so remove  them. the only file in the DOM folder should be the .js file. @fchinyanta Your validation is not meeting up with all the success criteria

**Comment by ToluEnny24** [comment]
@fchinyanta Are you fine? It's been a while. Is there any blockers? kindly reach out.

**Comment by ToluEnny24** [comment]
@fchinyanta How are you doing? any issues?

**Comment by Mayowa2020** [comment]
Hello @fchinyanta, I will be closing your PR so you can continue whenever you are available.

**Pull request closed without merging**
