### PR TITLE
[DGPFUS-166] Vendors Page Validation

### PR DESCRIPTION
**Pull request by agbajesilas**
-Added DOM task 1

Screenshot from 2023-06-24 00-42-54
Screenshot from 2023-06-24 00-43-06

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Well done @agbajesilas! Kindly ensure you run your test on your task.

**Comment by Mayowa2020** [comment]
Hello @agbajesilas, please reach out to me @Bukky on Slack, so we can look at this issue together.

**Comment by Mayowa2020** [comment]
Well done @agbajesilas! I noticed you did not attach the right screenshots to your PR. The screenshots you attached, are not for the Vendor Page.  You can confirm this by clicking on the Figma link. Please check out the required pages on Figma.

**Comment by agbajesilas** [comment]
> Well done @agbajesilas! I noticed you did not attach the right screenshots to your PR. The screenshots you attached, are not for the Vendor Page. You can confirm this by clicking on the Figma link. Please check out the required pages on Figma.
> 
> Peradventure you made a mistake with the PR title, you will need to create another PR with the right title. Also ensure your webpages are the same with what can be found on the Figma links.

**Pull request closed without merging**
