### PR TITLE
[NDFFET-160] My First Pull Request

### PR DESCRIPTION
**Pull request by Hossanna**
I have added some details about myself

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Hello @Hossanna, well done! But I am sorry, I will have to close your PR as you were instructed to clone and not to fork the repo. So kindly proceed to clone the repo and and create another PR. Before that, ensure you have deleted the Dufuna-CodeCamp-21 folder. Thank you!

**Comment by Hossanna** [comment]
Hello, thank you for your feedback, please I'm confused though.
I forked and cloned because that was what I saw in the material for this
topic, the topic resource on git and version control. So I followed the
steps exactly from there
It was forked, then cloned, then changes were made, added, committed,
pushed and then the PR was made.

If I'm only supposed to clone and not fork, would that mean that I'm to
open a new repo on my own github and how exactly am I cloning one repo and
pushing to another or would I be able to push back to the Dufuna repo? I
really don't understand please

Thank you as you clarify

**Comment by Mayowa2020** [comment]
Hello @Hossanna, if you are confused, you can reach out to me tomorrow on Slack @Bukky. I will walk you through it.

**Comment by Hossanna** [comment]
Thank you, I will do that.

**Pull request closed without merging**
