### PR TITLE
[DGPFUS-165] Responsive E-commerce Vendor Page

### PR DESCRIPTION
**Pull request by Bunmi194**

### CODE REVIEW

**Review by ToluEnny24 — CHANGES_REQUESTED** [review]
@Bunmi194 please effect the changes

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
@Bunmi194 Well done! It's good to inculcate good coding practices as much as possible:

1. Don’t mix CSS with HTML
2. You are better off using margin or padding than several line breaks.
3. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations.

**Comment by Mayowa2020** [comment]
@Bunmi194, hope you're doing great. I noticed that you are yet to effect the requested changes. Kindly do that and revert. Well done and keep pushing...

**Comment by Mayowa2020** [comment]
@Bunmi194, hope you are doing great. I noticed you are yet to effect the requested changes. Kindly do that and revert. Well done and keep pushing.

**Comment by Bunmi194** [comment]
@Mayowa2020 and @ToluEnny24 well noted. I've not been able to charge my laptop. I'll fix all issues as soon as possible, thanks.

**Pull request closed without merging**
