### PR TITLE
[TDSFET-110]  Product Array Algorithm

### PR DESCRIPTION
**Pull request by Olamide006**

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Hello @Olamide006, please remove the '<br>' from inside the quotes. Run your code again and attached the screenshots of your webpage to this PR.

**Comment by Olamide006** [comment]
algorithm

**Comment by Olamide006** [comment]
alogrithm1

**Review by Mayowa2020 — APPROVED** [review]
Well done @Olamide006! **Approved.**

**Pull request merged**
