### PR TITLE
[DGPFET-10] The Software Developer conditionals

### PR DESCRIPTION
**Pull request by Usmaniyya**
Kindly check my PR

### CODE REVIEW

**Review by ToluEnny24 — CHANGES_REQUESTED** [review]
@Usmaniyya Well done on this task however you have a codefactor error. The correct semantics should be if, else if, else if , else. So effect your changes

**Review by ToluEnny24 — COMMENTED** [review]
@Usmaniyya you are still having this codefactor error because you should have strictly equals to === not ==

**Comment by Usmaniyya** [comment]
Ok. Let me fix it..

**Comment by Usmaniyya** [comment]
Check now!!

**Comment by Usmaniyya** [comment]
Ok

**Pull request closed without merging**
