### PR TITLE
[NDFFET-168] Create the Cart Page with REACT 

### PR DESCRIPTION
**Pull request by Hossanna**
Screen Shot 2023-07-12 at 10 39 05 AM

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Hossanna! Where is the mobile view? As stated in the instructions, you are to ensure the page is also mobile responsive.  Kindly do that and attach the various screenshots of the screen views.

**Comment by Hossanna** [comment]
Screen Shot 2023-07-12 at 11 29 18 AM

**Comment by Hossanna** [comment]
Screen Shot 2023-07-14 at 2 28 56 PM

**Comment by Mayowa2020** [comment]
Hello @Hossanna, please ensure your code is running as it should. There's no correlation between the total cost of each item and the total costs of the items, as seen in the attached screenshot above.

**Comment by Hossanna** [comment]
Screen Shot 2023-09-19 at 10 14 10 AM

**Review by Mayowa2020 — APPROVED** [review]
Well done @Hossanna! For your next React task, you might have to create the app again as directed in the task. Please reach for further clarifications.

**Pull request merged**
