### PR TITLE
[DGPFUS-88] PHP Unit Converter

### PR DESCRIPTION
**Pull request by ChijiokeOrabueze**
In this PR,

- I wrote my first php code for unit conversion.

### CODE REVIEW

**Review by ToluEnny24 — CHANGES_REQUESTED** [review]
@ChijiokeOrabueze Why is this UsmanYahaya/aboutme.txt file deleted in your pull request?

**Comment by ChijiokeOrabueze** [comment]
> @ChijiokeOrabueze Why is this UsmanYahaya/aboutme.txt file deleted in your pull request?

@ToluEnny24 I made a pull of both master and my branch before starting my work. when i checkedout to my branch to pull, the file was flagged "D". I was of the opinion that the owner deleted it from his end. attached to this reply are pictures of my git bash commands. 
Capture1
Capture2
Capture3

**Comment by ToluEnny24** [comment]
This is because someone has tampered with the UsmanYahaya file

**Comment by ChijiokeOrabueze** [comment]
I noticed it. Before commiting my changes I double checked to be sure it was not from my end. 

- The file is not in my recycle bin. 
- git allowed me to pull after flagging the file with "D"(see first picture). If i had uncommited changes in my local directory, I wouldn't be able to pull. So i concluded it was from the owner.

**Review by ToluEnny24 — APPROVED** [review]

**Pull request merged**
