### PR TITLE
[WXSFUS-2] Develop a product page using HTML

### PR DESCRIPTION
**Pull request by chimmalambo**
- I created a product page using html
- screenshots of me performing task failed to upload here and so I also emailed them to Bukky in a word document..so here i only managed to attached screenshots after the fact 

image
image
image

### CODE REVIEW

**Comment by ToluEnny24** [comment]
Hi @chimmalambo well done on your task, I have the following comments, 
1) You added two folders (Html and html) which literally contains the same files. Delete one of the folders.
2) The success criteria of this task requires you use only two pictures, instead you added 6 images. Stick to two images, however for your personal lessons and development you can freestyle but do not push that to this repo.
3) For subsequent task, to get a screenshot on your laptop, use the snipping tool, once you type snipping tool on the search bar it shows you the app, you can create new shots of the intended page, save and you are good to go. 
Effect these changes and revert back to @Mayowa2020 soon

**Comment by chimmalambo** [comment]
Thanks. I didn't understand that about the update.

would it be possible to leave it with three images, as only 3 were used in
the task. one as a background image and 2 for the task as required?

I can simply remove the others which were not required.

let me know

**Review by chimmalambo — COMMENTED** [review]
@Mayowa2020 Hi Bukky. Does this correct for the errors? I left one additional image as I had a background image for the html webpage created.
I have noticed a logfile.json which seems to be related to a vendors page or something..do I simply delete that?

**Comment by chimmalambo** [comment]
could this pr be closed? I've tried deleting the folder and pushing again to the main repo but still having challenges.
I would like to try it again from scratch.
that would also allow me to redo the pr and take screenshots during the process as required by the task.

**Comment by ToluEnny24** [comment]
Hi @chimmalambo your files looks quite okay.

**Pull request merged**
