### PR TITLE
[TDSFUS -160] My First Pull Request

### PR DESCRIPTION
**Pull request by Haywhye12**
- This is my first pull request
- In this PR, I have add some details about myself.

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Well done @Haywhye12! You are to clone and not fork the repo. Kindly follow the instructions as directed in the task.

**Comment by Haywhye12** [comment]
Thank you for your response,

So what do i do now? Do i delete the repository

**Comment by Haywhye12** [comment]
I have corrected the error, Kindly check and let me access the next class

**Comment by Haywhye12** [comment]
I am having issues pushing to github.

When I enter 'git push origin about-ayomide'
It open up, sign in , and sign correctly but it fails on git bash.

info: please complete authentication in your browser...
remote: Permission to Dufuna-CodeCamp/Dufuna-CodeCamp-21.git denied to
Haywhye12.
fatal: unable to access '
https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21.git/': The requested
URL returned error: 403

**Pull request closed without merging**
