### PR TITLE
[JCRFUS-160] My First Pull Request.

### PR DESCRIPTION
**Pull request by yoneke**
- This is my first pull request
- In this PR, I have added some details about me.

### CODE REVIEW

**Review by kingpulani — APPROVED** [review]
Task completed

**Comment by ToluEnny24** [comment]
@yoneke I am Tolulope from Dufuna CodeCamp, and I am so sorry for the delay and experience you have had since October 15. I want to schedule you for a google meet tomorrow by 9:30am WAT is that fine. I will send the google meet link to you via slack.  Please on behalf of the entire team I apologize and really hope we can make it up to you ASAP. Thanks

**Comment by kingpulani** [comment]
Unfortunately I only have access to a computer from 12 pm to 6 pm.

**Comment by ToluEnny24** [comment]
@yoneke I suggested 9:30 so it would be an early solution. However 12:30pm is fine. 12:30 so you would have settled well with your laptop. See you tomorrow.

**Comment by ToluEnny24** [comment]
@yoneke  http://meet.google.com/azc-zsmr-qiv This is the link to the google meet. See you tomorrow God willing

**Pull request closed without merging**
