### PR TITLE
[TDSFET-164] Responsive E-commerce Landing Page

### PR DESCRIPTION
**Pull request by Olamide006**
Screenshot_20230730-190730_1
Screenshot_20230730-190740_1

Screenshot_20230730-190817_1

### CODE REVIEW

**Review by Mayowa2020 — COMMENTED** [review]
Well done, @Olamide006. Kindly reach me on Slack @Bukky, I have a few concerns about your assignment.

**Comment by Olamide006** [comment]
eee
eeee
tps://
dddd
github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/assets/110986372/30a1bddd-6b2a-4e0a-af4b-f8eb057c7675)

**Comment by Olamide006** [comment]
eee

**Comment by Olamide006** [comment]
Capturekk
Capturekkk
Capturek


Images for the tablet view

**Comment by Olamide006** [comment]
njnj
nmbl

**Review by Mayowa2020 — APPROVED** [review]
Well done @Olamide006! **Approved**

**Review by Mayowa2020 — APPROVED** [review]
Well done @Olamide006! **Approved.**

**Pull request merged**
