### PR TITLE
[DGPFUS-40] Querying the Transportation Database

### PR DESCRIPTION
**Pull request by Olabode969**

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done, @Olabode969! But the answer to the last question is incorrect. Please review your SQL query once again.
In the question, you are to get the id, names and the total number of passengers who paid a fare greater than $100 and above the age of 35 and had siblings or spouses on board?*. 

So, what I'm looking for is a list with the names and identification numbers of these passengers, along with their total number.

Kindly revert when you are done.

**Comment by Mayowa2020** [comment]
Hello @Olabode969, I have not seen any modifications to your solution in the last question. Apparently, the answer is not 15.

**Comment by Olabode969** [comment]
Hello @Mayowa2020 I just realized my mistake. I included passengers with parents and children. Please review again

**Review by Mayowa2020 — APPROVED** [review]
Well done, @Olabode969. **Approved**

**Pull request merged**
