### PR TITLE
[DGPFET-163] Create & Style the Vendors Page for a Food Orderin

### PR DESCRIPTION
**Pull request by mukhtarabdirahman**

### CODE REVIEW

**Review by ToluEnny24 — APPROVED** [review]
Manually reviewed..

**Comment by ToluEnny24** [comment]
@mukhtarabdirahman well done on this pr however you have 17 issues from codefactor that needs to be fixed. Do click on the details to guide you on the lines the errors are on and how to resolve it..

**Review by mukhtarabdirahman — COMMENTED** [review]
reviewde

**Review by mukhtarabdirahman — COMMENTED** [review]
correction made

**Review by mukhtarabdirahman — COMMENTED** [review]
vendors

**Review by mukhtarabdirahman — COMMENTED** [review]
line 74

**Review by ToluEnny24 — APPROVED** [review]
Manually reviewed...

**Pull request closed without merging**
