### PR TITLE
[DGPFET-168] Create the Cart Page with REACT

### PR DESCRIPTION
**Pull request by Chukwuebukaj**
Web capture_25-5-2022_154112_localhost

### CODE REVIEW

**Comment by Chukwuebukaj** [comment]
Web capture_25-5-2022_154411_localhost
Web capture_25-5-2022_154347_localhost
Web capture_25-5-2022_15437_localhost

**Comment by Chukwuebukaj** [comment]
[REACT.zip](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/files/8789280/REACT.zip)

**Comment by Chukwuebukaj** [comment]
> Hi @Chukwuebukaj Well done on your task. However, I can't see any of your files. You can drag and drop your files

Hi, @ToluEnny24 Thank you so much. I have dragged and dropped the files as instructed. Awaiting your feedback.

**Comment by ToluEnny24** [comment]
@Chukwuebukaj your file is still not in the right location. I tried fixing it for you but it is better I teach you how to do it. I will fix you for a meeting by 12:00pm on google meet. I will close this Pr so you will do it again. Before the meeting I want you to fix your all your .js files where you wrote === it should be ==
This is the http://meet.google.com/azc-zsmr-qiv

**Pull request closed without merging**
