### PR TITLE
Fix issue with setup around installing phantomjs

### PR DESCRIPTION
**Pull request by ToluAkin**

### CODE REVIEW

**Review by Ireti203 — APPROVED** [review]

**Comment by beccadaniel** [comment]
Nice one @ToluAkin .

**Comment by beccadaniel** [comment]
Just curious, what brought about the change?

**Comment by ToluAkin** [comment]
> Just curious, what brought about the change?

PhantomJs is deprecated and they had moved their package to phantomjs prebuit. The issue came up when a scholar was setting up on macos.

**Comment by beccadaniel** [comment]
Oh, that makes sense

**Comment by beccadaniel** [comment]
Thanks guys

**Pull request merged**
