### PR TITLE
[DGPFUS-110] Product Array Algorithm

### PR DESCRIPTION
**Pull request by chivicoko**
- created DSA1 directory
- added index.js file (the task algorithm) inside the DSA1 directory

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done, @chivicoko! Please attach a screenshot of  your webpage.

**Comment by chivicoko** [comment]
Okay. I thought it's just the JavaScript Algorithm that is required in the task

**Comment by chivicoko** [comment]
Screenshot (259)

**Review by Mayowa2020 — APPROVED** [review]
Well done, @chivicoko! **Approved**

**Pull request merged**
