### PR TITLE
[DGPFUS-165] Responsive E-commerce Vendor Page

### PR DESCRIPTION
**Pull request by Timilehin08**
Added responsiveness for small screens and tablet screen
bigdefaultscreens
1024screensabove2
1024screensabove
600pxscreens1
600pxscreens2
s

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Hello @Timilehin08 Well done! Adjust your view port for @media only screen and (min-width: 1200px) {...} to contain all the 4 elements in a row.

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Timilehin08! Kindly effect the requested changes as discussed and revert. You are to follow the given prototype.

**Comment by Timilehin08** [comment]
I've fixed the changes @Mayowa2020
bigscreenss
smallscreensss

**Comment by Timilehin08** [comment]
@Mayowa2020 I have made changes

**Review by Mayowa2020 — APPROVED** [review]
Well done @Timilehin08! Approved...

**Pull request merged**
