### PR TITLE
[BCCAMDT-2] Develop Product  a Product Page using HTML

### PR DESCRIPTION
**Pull request by mchabo**
Screenshot (1)
Screenshot (2)
Screenshot (3)
Screenshot (4)

### CODE REVIEW

**Comment by Dufuna-Fem** [comment]
@mchabo  Welldone. It looks like you did not run the test for your task. You can find the test in the path `test/product_page_using_html`. Once you do that, you can update your pull request.

**Comment by mchabo** [comment]
> @mchabo Welldone. It looks like you did not run the test for your task. You can find the test in the path `test/product_page_using_html`. Once you do that, you can update your pull request.

In the Dufuna folder that path is not there, there is only test/my_first_pull_request

**Comment by Dufuna-Fem** [comment]
You need to update your repository by pulling from the `master` branch. The tests are currently on `master`. Follow these steps:

- checkout to the master branch using the appropriate command
- pull from the master branch using `git pull origin master`
- checkout back to this branch you're working on
- run this command `git merge master`
At this point, if you have no conflicts you should be able to see the required tests.

**Comment by Dufuna-Fem** [comment]
If you run into any issues, please reach out on slack to either @Folashade or @Ireti

**Comment by mchabo** [comment]
When I press enter nothing is happening

**Pull request merged**
