### PR TITLE
[NDFFET-167] Vendors Page Validation

### PR DESCRIPTION
**Pull request by Hossanna**
Screen Shot 2023-06-16 at 10 19 55 PM

### CODE REVIEW

**Comment by Hossanna** [comment]
Screen Shot 2023-06-18 at 10 24 32 PM

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done @Hossanna!  Please remove the unused codes from your PR.

**Comment by Hossanna** [comment]
Thank you! I have done that @Mayowa2020

**Comment by Mayowa2020** [comment]
Well done @Hossanna! Please correct the Code Factor error displayed above.

**Review by Mayowa2020 — APPROVED** [review]
Well done @Hossanna! **Approved.**

**Pull request merged**
