### PR TITLE
[HIRFUS-167] Vendors Page Validation

### PR DESCRIPTION
**Pull request by AaronAsborn**
Screenshot 2022-04-27 at 16-01-10 FoodBag Vendors

### CODE REVIEW

**Comment by ToluEnny24** [comment]
Well done @AaronAsborn you have a codefactor error to fix and also the styling you used for the remove feature does not in any way look like the figma design, please effect the requested changes

**Comment by AaronAsborn** [comment]
Noted

**Comment by AaronAsborn** [comment]
Screenshot from 2022-04-28 12-42-52
Screenshot from 2022-04-28 12-42-45

**Review by ToluEnny24 — APPROVED** [review]
Approved

**Pull request merged**
