### PR TITLE
[DGPFUS-170] Create the Success page using REACT

### PR DESCRIPTION
**Pull request by chivicoko**
- added a success page

Screenshot (199)
Screenshot (198)
Screenshot (197)

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Bravo, @chivicoko! Your CSS file including your media query is not visible to me. I'd also like to see the screenshots of your web pages display/show the dimensions of the different screen sizes. 

Kindly make the requested and revert when done.

**Comment by chivicoko** [comment]
@Mayowa2020 I didn't really use mediaquery here

**Comment by chivicoko** [comment]
- I also screenshotted the screen sizes along with the different page views

Screenshot (200)
Screenshot (201)
Screenshot (202)
Screenshot (203)

**Comment by Mayowa2020** [comment]
Noted @chivicoko! But what's the dimension of your mobile webpage above, it's not showing in the screenshot above.

**Comment by chivicoko** [comment]
@Mayowa2020 , it's 419px by 663px
it's showing at the top of the 'sign up' button there

**Review by Mayowa2020 — APPROVED** [review]
Well done, @chivicoko! **Approved.**

**Pull request merged**
