### PR TITLE
[HIRFUS-111] Develop a Customer details list view page

### PR DESCRIPTION
**Pull request by Edwin-Ngoma**
- customers php created
Screenshot (1)

### CODE REVIEW

**Comment by Mayowa2020** [comment]
Hello @Edwin-Ngoma, There is no log file present in this pull request. Please ensure that you run the tests locally and revert when done.

**Comment by Edwin-Ngoma** [comment]
- Sorry but i am unnable to locate the test  files for php databases

Screenshot (3)

**Comment by Edwin-Ngoma** [comment]
Hello,

 There's been  errors in our code streams, we've been pushing without logfiles for a while now.

 I'm not sure if Tolulope had explained this to you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by ToluEnny24 — APPROVED** [review]
Manually reviewed...

**Pull request merged**
