### PR TITLE
[NDFFET-165] Responsive E-commerce Vendor Page

### PR DESCRIPTION
**Pull request by Esther9013**
this is a PR for creating a responsive e-commerce vendor page using HTML and CSS and below is the screenshot of the result.

vendor-4
vendor-9
vendor-12
vendor-15
vendor-13
vendor-17

-images.githubusercontent.com/107318062/187968161-c27ab8ed-2c4c-47e1-b486-91c9cf71544f.PNG)
vendor-14

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Please use the common breakpoints for the widths of devices:

320px — 480px: Mobile devices
481px — 768px: iPads, Tablets
769px — 1024px: Small screens, laptops
1025px — 1200px: Desktops, large screens
1201px and more —  Extra large screens, TV

OR this 

/* Extra small devices (phones, 600px and down) */
@media only screen and (max-width: 600px) {...}

/* Small devices (portrait tablets and large phones, 600px and up) */
@media only screen and (min-width: 600px) {...}

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) {...}

/* Large devices (laptops/desktops, 992px and up) */
@media only screen and (min-width: 992px) {...}

/* Extra large devices (large laptops and desktops, 1200px and up) */
@media only screen and (min-width: 1200px) {...}

**Comment by Mayowa2020** [comment]
Please do the requested changes  and revert when done. Thanks!

**Comment by Esther9013** [comment]
> Please do the requested changes and revert when done. Thanks!

I've done the requested changes ma'am

**Review by Mayowa2020 — APPROVED** [review]
Well done @Esther9013 ! Approved..

**Pull request merged**
