### PR TITLE
[HIRFUS-163] Create & Style the Vendors Page for a Food Orderin

### PR DESCRIPTION
**Pull request by AaronAsborn**
i Created a vendor page for food bag

### CODE REVIEW

**Comment by ToluEnny24** [comment]
@AaronAsborn well done. I have the following comments. Why are you pushing from a forked repo and not a cloned repo?
Then you have two failed tests, what tests are failing?

**Comment by AaronAsborn** [comment]
It says the words food and bag are not on the page
2. It also said a line below the first set of images is missing.
To resolve the issue I tried both the <hr> tag and making a border-top
line. But none of them worked.

About the forked and cloning. I forked the repo remotely and then cloned
the the forked one to my desktop.

**Comment by ToluEnny24** [comment]
@AaronAsborn For your next task delete the dufuna folder you have on your local machine. and reclone the original repo. Go through the instructions on your readme.md in the repo on how to push correctly. If not you will keep having conflicting files. Concerning the test script, we will see what can be done.

**Review by ToluEnny24 — APPROVED** [review]
Well done @AaronAsborn

**Pull request merged**
