### PR TITLE
[DCSFUS-160] My First Pull Request

### PR DESCRIPTION
**Pull request by olamy09**
My first pull request
Added details about myself

### CODE REVIEW

**Review by Mayowa2020 — CHANGES_REQUESTED** [review]
Well done, @olamy09! Apparently, I can see two aboutme.txt files in your PR. Kindly remove the one directly in the general submissions folder. I am ok with the one in your folder.

**Comment by olamy09** [comment]
alright thanks but on the app, its still showing pending.

**Comment by Mayowa2020** [comment]
Hello, @olamy09 It's showing pending because it's not been approved and merged.  I noticed there are also conflicts that need to be resolved. The conflicts can be resolved from my end, but I will need to make the requested changes, so I can approve and merge your PR.

**Comment by olamy09** [comment]
i have deleted the one on the general submission folder. Please kindly help
me work on merging so i can proceed with my learning, thanks

**Comment by Mayowa2020** [comment]
Hello @olamy09, You are yet to make the requested changes.

**Comment by olamy09** [comment]
what other changes am i left with??. I have deleted the one on the General
folder and i have also deleted my local repository as well

**Comment by Mayowa2020** [comment]
The changes you made do not reflect in your PR . You will need to run git status, git add <filename> git commit and then git push to update the changes so that the changes can reflect in your PR.

**Comment by Mayowa2020** [comment]
What's your username on Slack? We need to chat. I noticed you forked the instead of cloning it. This task was not correctly done. Please reach out to me at @Bukky on Slack.

**Comment by olamy09** [comment]
This is outrightly confusing already. I dont have a slack account. Send me your number let me chat you on whatsapp

**Comment by olamy09** [comment]
Am thinking of deleting all and re-run from scratch, what do you feel ma'am. Please help reply asap. I want to move pass this level Thanks

**Comment by Mayowa2020** [comment]
Hello @olamy09, You must register a Slack account because it is the program's official channel for communication. This is where all program-related announcements are issued. You can't go on a walk in isolation.

Also, you need to close this PR, delete the repo you forked, and start afresh. But this time, make sure you clone the repo. Once you follow the guidelines stated in the task, your PR should merge automatically, and the next module will be opened automatically too.

**Pull request closed without merging**
