### PR TITLE
my first commit, added an aboutMe text

### PR DESCRIPTION
**Pull request by imadeleo**

### CODE REVIEW

**Comment by ToluEnny24** [comment]
@imadeleo Well done on your first pull request. However, I will be closing this pull request because:
1) You are pushing from a forked repo. You are to clone the Dufuna-CodeCamp/Dufuna-CodeCamp21 repository not imadeleo/Dufuna-CodeCamp21. Delete the one you have on your local machine and reclone.
2) You used the wrong PR title. Your title should be [AlphanumericCode] A Title as seen on the app It should not be my first commit, added an aboutMe text.

**Comment by imadeleo** [comment]
Good day admin,

Each time I use the ./test.sh command code I get 3 failed test instead of 3 passed test. I attached a photo of it to this mail. I am really confused.

Thanks

**Comment by ToluEnny24** [comment]
@imadeleo I am @Tolulope on slack on the Dufuna Workspace I have been trying to find  a way to reach out to you. You are doing a couple of wrong things and I hope to help you get things right.

**Comment by imadeleo** [comment]
Alright. Please what are the issues because I have been stuck at it for sometime now

**Comment by ToluEnny24** [comment]
@imadeleo You need to watch your videos again, and read the readme.md file in the Dufuna CodeCamp21repository on your local machine. If you are still stuck, I can fix a time out with you by 4pm WAT today.

**Comment by imadeleo** [comment]
Let me do that right away. I will let you know if the issue persists before the said time.

**Comment by ToluEnny24** [comment]
Please what is your email address?

**Comment by ToluEnny24** [comment]
Hi @imadeleo I will appreciate if you send your messages directly on the slack workspace. So a solution can be proffered to you once and for all. Please do reach out on the slack workspace. or send an email directly to tolulope@dufuna.org

**Pull request closed without merging**
